//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectRAM.Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectRAM.Editor.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About program.
        /// </summary>
        public static string aboutProgram {
            get {
                return ResourceManager.GetString("aboutProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument.
        /// </summary>
        public static string argument {
            get {
                return ResourceManager.GetString("argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string command {
            get {
                return ResourceManager.GetString("command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complexity report.
        /// </summary>
        public static string complexityReport {
            get {
                return ResourceManager.GetString("complexityReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything is alright.
        /// </summary>
        public static string everythingAlright {
            get {
                return ResourceManager.GetString("everythingAlright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to file.
        /// </summary>
        public static string exportToFile {
            get {
                return ResourceManager.GetString("exportToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found 1 error in the code.
        /// </summary>
        public static string foundError {
            get {
                return ResourceManager.GetString("foundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} errors in the code.
        /// </summary>
        public static string foundErrors {
            get {
                return ResourceManager.GetString("foundErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from file.
        /// </summary>
        public static string importFromFile {
            get {
                return ResourceManager.GetString("importFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from input tape file.
        /// </summary>
        public static string importInputTape {
            get {
                return ResourceManager.GetString("importInputTape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input tape.
        /// </summary>
        public static string inputTape {
            get {
                return ResourceManager.GetString("inputTape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string label {
            get {
                return ResourceManager.GetString("label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string line {
            get {
                return ResourceManager.GetString("line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory.
        /// </summary>
        public static string memory {
            get {
                return ResourceManager.GetString("memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file.
        /// </summary>
        public static string newFile {
            get {
                return ResourceManager.GetString("newFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        public static string openFile {
            get {
                return ResourceManager.GetString("openFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output tape.
        /// </summary>
        public static string outputTape {
            get {
                return ResourceManager.GetString("outputTape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output tape is too large. Aborting.
        /// </summary>
        public static string outputTapeOverflow {
            get {
                return ResourceManager.GetString("outputTapeOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print program.
        /// </summary>
        public static string printProgram {
            get {
                return ResourceManager.GetString("printProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        public static string program {
            get {
                return ResourceManager.GetString("program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run program.
        /// </summary>
        public static string runProgram {
            get {
                return ResourceManager.GetString("runProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file.
        /// </summary>
        public static string saveFile {
            get {
                return ResourceManager.GetString("saveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file as.
        /// </summary>
        public static string saveFileAs {
            get {
                return ResourceManager.GetString("saveFileAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop program.
        /// </summary>
        public static string stopProgram {
            get {
                return ResourceManager.GetString("stopProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch editor.
        /// </summary>
        public static string switchEditor {
            get {
                return ResourceManager.GetString("switchEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string tools {
            get {
                return ResourceManager.GetString("tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification.
        /// </summary>
        public static string verification {
            get {
                return ResourceManager.GetString("verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification report.
        /// </summary>
        public static string verificationReport {
            get {
                return ResourceManager.GetString("verificationReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify program.
        /// </summary>
        public static string verifyProgram {
            get {
                return ResourceManager.GetString("verifyProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in.
        /// </summary>
        public static string zoomIn {
            get {
                return ResourceManager.GetString("zoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out.
        /// </summary>
        public static string zoomOut {
            get {
                return ResourceManager.GetString("zoomOut", resourceCulture);
            }
        }
    }
}
